CREATE DATABASE TREINO
USE TREINO

CREATE TABLE CIDADE
(
	ID_CIDADE INT NOT NULL PRIMARY KEY,
	NOME_CIDADE VARCHAR(60) NOT NULL,
	UF VARCHAR(2) NOT NULL
)

CREATE TABLE CLIENTE
(
	ID_CLIENTE INT IDENTITY(1,1) NOT NULL,
	NOME_CLIENTE VARCHAR(60)NOT NULL,
	ENDERECO VARCHAR(60) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CIDADE INT NOT NULL,
	CEP VARCHAR(9),
	CONSTRAINT PK_CLI1 PRIMARY KEY (ID_CLIENTE),
	CONSTRAINT FK_CLI1 FOREIGN KEY (ID_CIDADE) 
	REFERENCES CIDADE(ID_CIDADE)
)

CREATE TABLE VENDEDORES
(
	ID_VENDEDOR INT IDENTITY(1,1) NOT NULL,
	NOME_VENDED VARCHAR(60)NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
	CONSTRAINT PK_VEN1 PRIMARY KEY (ID_VENDEDOR)
)

CREATE TABLE VENDAS
(
	NUM_VEND INT IDENTITY(1,1) NOT NULL,
	DATA_VEN DATETIME NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_VENDED INT NOT NULL,
	STATUS CHAR(1),
	CONSTRAINT PK_VENDAS1 PRIMARY KEY (NUM_VEND),
	CONSTRAINT FK_VENDAS1 FOREIGN KEY (ID_CLIENTE) 
	REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT FK_VENDAS2 FOREIGN KEY (ID_VENDED) 
	REFERENCES VENDEDORES(ID_VENDEDOR)
)

CREATE TABLE CATEGORIA
(
	ID_CATEGORIA INT NOT NULL PRIMARY KEY,
	NOME_CATEGORIA VARCHAR(20) NOT NULL
)

CREATE TABLE UNIDADE
(
	ID_UNIDADE VARCHAR(3) NOT NULL PRIMARY KEY,
	DESC_UNIDADE VARCHAR(25) NOT NULL
)

CREATE TABLE PRODUTOS
(
	ID_PROD INT IDENTITY(1,1) NOT NULL,
	NOME_PROD VARCHAR(50) NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	ID_UNIDADE VARCHAR(3) NOT NULL,
	PRECO DECIMAL(10,2),
	CONSTRAINT PK_PRODUTOS1 PRIMARY KEY (ID_PROD),
	CONSTRAINT FK_PRODUTOS1 FOREIGN KEY (ID_CATEGORIA) 
	REFERENCES CATEGORIA(ID_CATEGORIA),
	CONSTRAINT FK_PRODUTOS2 FOREIGN KEY (ID_UNIDADE) 
	REFERENCES UNIDADE(ID_UNIDADE)
)

CREATE TABLE VENDA_ITENS
(
	NUM_VE INT NOT NULL,
	NUM_SE INT IDENTITY(1,1) NOT NULL,
	ID_PROD INT NOT NULL,
	QTDE DECIMAL(10,2) NOT NULL,
	VAL_UNI DECIMAL(10,2) NOT NULL,
	VAL_TOT DECIMAL(10,2),
	CONSTRAINT PK_VENDA_ITENS1 PRIMARY KEY (NUM_VE,NUM_SE),
	CONSTRAINT FK_VENDA_ITENS1 FOREIGN KEY (NUM_VE) 
	REFERENCES VENDAS(NUM_VEND),
	CONSTRAINT FK_VENDA_ITENS2 FOREIGN KEY (ID_PROD) 
	REFERENCES PRODUTOS(ID_PROD)
)